name: Test and Deploy

on:
    push:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "20"

            - name: Install Dependencies
              run: npm install

            - name: Run Tests
              run: npm test

    deploy:
        needs: test
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "20"

            - name: Install Dependencies
              run: npm install

            - name: Build
              run: npm run build

            - name: Deploy to S3
              uses: jakejarvis/s3-sync-action@v0.6.0
              with:
                  args: --acl public-read --delete
              env:
                  AWS_S3_BUCKET: zitda
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  SOURCE_DIR: "build"
